name: Build and Publish ESPHome firmware and website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.yaml'

jobs:
  publish-everything-presence-lite-ha:
    name: Publish Everything Presence Lite HA
    uses: EverythingSmartHome/everything-presence-lite/.github/workflows/esphome-build.yml@main
    with:
      files: everything-presence-lite-ha.yaml
      name: Everything Presence Lite HA
      manifest_filename: everything-presence-lite-ha-manifest.json
      clean: false
      esphome_version: latest
      directory_name: everything-presence-lite-ha
  publish-everything-presence-lite-ha-no-ble:
    name: Publish Everything Presence Lite HA No BLE
    uses: EverythingSmartHome/everything-presence-lite/.github/workflows/esphome-build.yml@main
    with:
      files: everything-presence-lite-ha-no-ble.yaml
      name: Everything Presence Lite HA No BLE
      manifest_filename: everything-presence-lite-ha-no-ble-manifest.json
      clean: false
      esphome_version: latest
      directory_name: everything-presence-lite-ha-no-ble
  publish-everything-presence-lite-ha-ld2410:
    name: Publish Everything Presence Lite HA LD2410
    uses: EverythingSmartHome/everything-presence-lite/.github/workflows/esphome-build.yml@main
    with:
      files: everything-presence-lite-ha-ld2410.yaml
      name: Everything Presence Lite HA LD2410
      manifest_filename: everything-presence-lite-ha-ld2410-manifest.json
      clean: false
      esphome_version: latest
      directory_name: everything-presence-lite-ha-ld2410
  publish-everything-presence-lite-ha-ld2410-no-ble:
    name: Publish Everything Presence Lite HA LD2410 No BLE
    uses: EverythingSmartHome/everything-presence-lite/.github/workflows/esphome-build.yml@main
    with:
      files: everything-presence-lite-ha-ld2410-no-ble.yaml
      name: Everything Presence Lite HA LD2410 No BLE
      manifest_filename: everything-presence-lite-ha-ld2410-no-ble-manifest.json
      clean: false
      esphome_version: latest
      directory_name: everything-presence-lite-ha-ld2410-no-ble
  publish-everything-presence-lite-ha-sen0395:
    name: Publish Everything Presence Lite HA SEN0395
    uses: EverythingSmartHome/everything-presence-lite/.github/workflows/esphome-build.yml@main
    with:
      files: everything-presence-lite-ha-sen0395.yaml
      name: Everything Presence Lite HA SEN0395
      manifest_filename: everything-presence-lite-ha-sen0395-manifest.json
      clean: false
      esphome_version: latest
      directory_name: everything-presence-lite-ha-sen0395
  publish-everything-presence-lite-ha-sen0395-no-ble:
    name: Publish Everything Presence Lite HA SEN0395 No BLE
    uses: EverythingSmartHome/everything-presence-lite/.github/workflows/esphome-build.yml@main
    with:
      files: everything-presence-lite-ha-sen0395-no-ble.yaml
      name: Everything Presence Lite HA SEN0395 No BLE
      manifest_filename: everything-presence-lite-ha-sen0395-no-ble-manifest.json
      clean: false
      esphome_version: latest
      directory_name: everything-presence-lite-ha-sen0395-no-ble
