name: Build and Publish ESPHome firmware and website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.yaml'

jobs:
  publish-everything-presence-lite:
    name: Publish Everything Presence Lite
    uses: EverythingSmartHome/everything-presence-lite/.github/workflows/esphome-build.yml@main
    with:
      files: everything-presence-lite-ha.yaml
      name: Everything Presence Lite HA
      manifest_filename: everything-presence-lite-ha-manifest.json
      clean: false
      esphome_version: latest
      directory_name: everything-presence-lite-ha
  publish-everything-presence-lite-ha-no-ble:
    name: Publish Everything Presence Lite No BLE
    uses: EverythingSmartHome/everything-presence-lite/.github/workflows/esphome-build.yml@main
    with:
      files: everything-presence-lite-ha-no-ble.yaml
      name: Everything Presence Lite No BLE
      manifest_filename: everything-presence-lite-ha-no-ble-manifest.json
      clean: false
      esphome_version: latest
      directory_name: everything-presence-lite-ha-no-ble
#  publish-everything-presence-one-ha-beta:
#    name: Publish Everything Presence One Home Assistant Beta
#    uses: esphome/workflows/.github/workflows/publish.yml@main
#    with:
#      files: everything-presence-one-beta.yaml
#      name: Everything Presence One HA Beta
#      manifest_filename: everything-presence-one-ha-beta-manifest.json
#      clean: false
#      esphome_version: latest
